#!/usr/bin/python

import sqlite3

conn = sqlite3.connect('test.db')
print "Database opened successfully"

conn.execute('''CREATE TABLE STUDENT
       (ROLL_NO INT PRIMARY KEY NOT NULL,
        NAME VARCHAR(20) NOT NULL,
        AGE  INT NOT NULL,
        ADDRESS CHAR(50),
        MARKS REAL);''')
print "Table created successfully";

conn.close()
