#!/usr/bin/python

import sqlite3

conn = sqlite3.connect('test.db')
print "Opened database successfully";


cursor = conn.execute("SELECT roll_no, name, address, marks from STUDENT")
print "Record Before Updation"
for row in cursor:
   print "ROLL_NO = ", row[0]
   print "NAME = ", row[1]
   print "ADDRESS = ", row[2]
   print "SALARY = ", row[3], "\n"


#Delete Record from table
conn.execute("DELETE from STUDENT where roll_no=2;")
conn.commit
print "\nTotal number of rows deleted :", conn.total_changes

cursor = conn.execute("SELECT roll_no, name, address, marks from STUDENT")
print "\n Table After Deletion"
for row in cursor:
   print "ROLL_NO = ", row[0]
   print "NAME = ", row[1]
   print "ADDRESS = ", row[2]
   print "SALARY = ", row[3], "\n"

print "Operation done successfully";
conn.close()
