#!/usr/bin/python

import sqlite3

conn = sqlite3.connect('test.db')
print "Opened database successfully";

cursor = conn.execute("SELECT roll_no, name,age, address, marks from STUDENT where roll_no=1")
print "Record Before Updation"
for row in cursor:
   print "ROLL_NO = ", row[0]
   print "NAME = ", row[1]
   print "AGE = ", row[2]
   print "ADDRESS = ", row[3]
   print "MARKS = ", row[4], "\n"

print "Operation done successfully";


#Update an existing record
conn.execute("UPDATE STUDENT set name = 'Abhijit',address='145,Subhash Nagar' where roll_no=1")
conn.commit
print "Total number of rows updated :", conn.total_changes

cursor = conn.execute("SELECT roll_no, name,age, address, marks from STUDENT where roll_no=1")
print "\n Record After Updation"
for row in cursor:
   print "ROLL_NO = ", row[0]
   print "NAME = ", row[1]
   print "AGE = ", row[2]
   print "ADDRESS = ", row[3]
   print "MARKS = ", row[4], "\n"

print "Operation done successfully";
conn.close()
